spring.application.name=User_Search

# URL ? ????? ????? ????
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=almaz
spring.datasource.password=${DB_PASSWORD}

# ????????? Hibernate ????????????? ?????????/????????? ???????
spring.jpa.hibernate.ddl-auto=update
# ?????????? SQL-??????? ? ??????? (?????? ??? ???????)
spring.jpa.show-sql=true